name: .NET Framework Desktop

on:
 push:
 branches: [ "main" ]

jobs:

 build:

 strategy:
  matrix:
    configuration: [Debug, Release]

 runs-on: windows-latest

 env:
  Solution_Name: /MathGPTProGenerator.csproj

 steps:
 - name: Checkout
  uses: actions/checkout@v3
  with:
    fetch-depth: 0

 - name: Install .NET Framework
  uses: actions/setup-dotnet@v3
  with:
    dotnet-version: '4.6.1'

 - name: Build
  run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }}

 - name: Run
  run: start cmd /c MathGPTProGenerator.exe
