name: .NET Core Desktop

on:
 push:
 branches: [ "main" ]
 pull_request:
 branches: [ "main" ]

jobs:

 build:

 strategy:
   matrix:
     configuration: [Debug, Release]

 runs-on: windows-latest

 env:
   Solution_Name: /MathGPTProGenerator.csproj

 steps:
 - name: Checkout
   uses: actions/checkout@v3
   with:
     fetch-depth: 0

 - name: Install .NET Core
   uses: actions/setup-dotnet@v3
   with:
     dotnet-version: 6.0.x

 - name: Build
   run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }}

 - name: Run
   run: dotnet run --project $env:Solution_Name
