name: .NET Framework Desktop

on:
 push:
  branches: [ "main" ]
 pull_request:
  branches: [ "main" ]

jobs:

 build:

  strategy:
    matrix:
      configuration: [Debug, Release]

  runs-on: windows-latest

  env:
    Solution_Name: /MathGPTProGenerator.csproj

  steps:
  - name: Checkout
    uses: actions/checkout@v3
    with:
      fetch-depth: 0

  - name: Setup MSBuild
    uses: microsoft/setup-msbuild@v1

  - name: Restore dependencies
    run: msbuild $env:Solution_Name /t:Restore

  - name: Restore
    run: dotnet restore $env:Solution_Name
