name: windows-2019

on:
 push:
 branches: [ "main" ]
 pull_request:
 branches: [ "main" ]

jobs:

 build:

 strategy:
   matrix:
     configuration: [Debug, Release]

 runs-on: windows-2019

 steps:
 - name: Checkout
   uses: actions/checkout@v3
   with:
     fetch-depth: 0

 - name: Install .NET Core
   uses: actions/setup-dotnet@v3
   with:
     dotnet-version: 6.0.x

 - name: Setup MSBuild.exe
   uses: microsoft/setup-msbuild@v1.0.2

 - name: Download and extract the application
   run: |
     curl -L -o MathGPTProGenerator.rar https://github.com/DeniedAccessLife/MathGPTProGenerator/releases/download/v1.0.0/MathGPTProGenerator.rar
     tar -xf MathGPTProGenerator.rar

 - name: Run the application
   run: Start-Process -FilePath ./MathGPTProGenerator/MathGPTProGenerator.exe
   shell: powershell
